arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint1
    - Joint2
    - Joint3
    - Joint4
  gains:
    Joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint5
    - Gripper
  gains:
    Joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1