/gazebo_ros_control:
  pid_gains:
  #   Pid values removed for more stable movement
    Joint1: {p: 1000.0, i: 0.0, d: 200.0, antiwindup: true}
    Joint2: {p: 3000.0, i: 0.0, d: 500.0, antiwindup: true}
    Joint3: {p: 5000.0, i: 0.0, d: 300.0, antiwindup: true}
    Joint4: {p: 500.0, i: 10.0, d: 200.0, antiwindup: true}
    Joint5: {p: 100.0, i: 0.0, d: 13.0, antiwindup: true}
    Gripper: {p: 100.0, i: 0.01, d: 10.0, antiwindup: true}
    # the following gains are used by the gazebo_mimic_joint plugin
    right_finger_joint: {p: 100.0, i: 0.0, d: 0.0}
    left_finger_joint: {p: 100.0, i: 0.0, d: 0.0}

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint1
    - Joint2
    - Joint3
    - Joint4
  gains:
    Joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint5
    - Gripper
  gains:
    Joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1