<?xml version="1.0" ?>

<robot name="lynxmotion_al5d" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find lynxmotion_al5d_description)/urdf/lynxmotion_al5d_properties.urdf.xacro" />

    <!-- Base link comprising the board behind the robot and the cylinder at its bottom -->
    <link name="robot_support">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/support.dae" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/support.dae" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>
        <xacro:inertial_matrix mass="${base_mass + board_mass}" ixx="3.6565e-7" ixy="-3.72e-9" ixz="1e-6" iyy="9.404e-8" iyz="4.375e-8" izz="4.1776e-7" xyz="0.000585 0.0602746 0.0170628" />
    </link>
    <gazebo reference="robot_support" />

    <link name="robot_base_cylinder">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/rotation_cylinder.dae" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 -0.021 0" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/rotation_cylinder.dae" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 -0.021 0" />
        </collision>
        <xacro:inertial_matrix_bis mass="0.01" />
    </link>
    <gazebo reference="robot_base_cylinder" />

    <link name="robot_base_top_box">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/top_box.dae" />
            </geometry>
            <origin xyz="-0.01 0.03 0" rpy="0 0 ${PI}" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/top_box.dae" />
            </geometry>
            <origin xyz="-0.01 0.03 0" rpy="0 0 ${PI}" />
        </collision>
        <xacro:inertial_matrix_bis mass="${top_box_mass}" />
    </link>
    <gazebo reference="robot_base_top_box" />

    <link name="shoulder">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/shoulder.dae" />
            </geometry>
            <origin rpy="${-5*PI/8} 0 0" xyz="0.005 -0.0625 0.036" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/shoulder.dae" />
            </geometry>
            <origin rpy="${-5*PI/8} 0 0" xyz="0.005 -0.0625 0.036" />
        </collision>
        <xacro:inertial_matrix_bis mass="${shoulder_mass}" />
    </link>
    <gazebo reference="shoulder" />

    <link name="elbow">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/elbow.dae" />
            </geometry>
            <origin rpy="${-PI-0.895} ${PI} 0" xyz="-0.006 ${tube_length - 2*hs_755eb_depth/5} ${-shoulder_to_elbow - 0.018}" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/elbow.dae" />
            </geometry>
            <origin rpy="${-PI-0.895} ${PI} 0" xyz="-0.005 ${tube_length - 2*hs_755eb_depth/5 + 0.005} ${-shoulder_to_elbow - 0.02} " />
        </collision>
        <xacro:inertial_matrix_bis mass="${hs_755eb_mass + hs_645_mass}" />
    </link>
    <gazebo reference="elbow" />

    <link name="wrist">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/wrist.dae" />
            </geometry>
            <origin rpy="${PI} 0 0" xyz="0.005 -0.165 0.0695" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/wrist.dae" />
            </geometry>
            <origin rpy="${PI} 0 0" xyz="0 -0.165 0.067" />
        </collision>
        <xacro:inertial_matrix_bis mass="0.031" />
    </link>
    <gazebo reference="wrist" />

    <link name="gripper">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/gripper.dae" />
            </geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0 -0.02 0.0" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/gripper.dae" />
            </geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0 -0.02 0" /> <!---0.021 -0.005" /> -->
        </collision>
        <xacro:inertial_matrix_bis mass="0.042" />
    </link>
    <gazebo reference="gripper" />

    <link name="left_finger">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/finger_left.dae" />
            </geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0.001 -0.005 0" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/finger_left.dae" />
            </geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0.001 -0.005 0" />
        </collision>
        <xacro:inertial_matrix_bis mass="0.002" />
    </link>
    <gazebo reference="left_finger" />
            
    <link name="right_finger">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/finger_right.dae" />
            </geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="-0.003 -0.005 0" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/finger_right.dae" />
            </geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="-0.003 -0.005 0" />
        </collision>
        <xacro:inertial_matrix_bis mass="0.002" />
    </link>
    <gazebo reference="right_finger" />

    <!-- Dummy link used for the gripper -->
    <link name="gripper_mov">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.01 0.01 0.01" />
            </geometry>
            <material name="transparent">Gazebo/GreyTransparent</material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.01 0.01 0.01" />
            </geometry>
        </collision>
        <xacro:inertial_matrix_box mass="0.01" width="0.01" height="0.01" depth="0.01" />
    </link>
    <gazebo reference="gripper_mov" />
    <!-- Adding joints -->
    <joint name="Joint1" type="revolute">
        <parent link="robot_support" />
        <child link="robot_base_cylinder" />
        <axis xyz="0 0 -1" />
        <origin xyz="0 0.02 0" rpy="0 0 ${PI}" />
        <limit effort="100" velocity="3" lower="${-PI}" upper="${PI}" />
        <dynamics damping="50.0" friction="1" />
    </joint>

    <joint name="base_to_cylinder" type="fixed">
        <parent link="robot_base_cylinder" />
        <child link="robot_base_top_box" />
        <dynamics damping="1.0" friction="0.8" />
    </joint>
 
    <joint name="Joint2" type="revolute">
        <parent link="robot_base_top_box" />
        <child link="shoulder" />
        <axis xyz="1 0 0" />
        <origin xyz="0 0.02 0.07" />
        <limit effort="100" lower="0" upper="${PI}" velocity="3" />
        <dynamics damping="1.0" friction="0.8" />
    </joint>

    <joint name="Joint3" type="revolute">
        <parent link="shoulder" />
        <child link="elbow" />
        <axis xyz="1 0 0" />
        <origin xyz="0 ${shoulder_to_elbow} 0" />
        <limit effort="100" lower="${-PI}" upper="0" velocity="3" />
        <dynamics damping="1.0" friction="0.8" />
    </joint>

    <joint name="Joint4" type="revolute">
        <parent link="elbow" />
        <child link="wrist" />
        <axis xyz="1 0 0" />
        <origin rpy="0 0 0" xyz="0 0.181 0.005" />
        <limit effort="40" lower="${-PI/2}" upper="${PI/2}" velocity="3" />
        <dynamics damping="5.0" friction="0.08" />
    </joint>

    <joint name="Joint5" type="revolute">
        <parent link="wrist" />
        <child link="gripper" />
        <axis xyz="0 -1 0" />
        <origin rpy="0 0 ${PI}" xyz="0 0.04 0" />
        <limit effort="100" lower="${-PI}" upper="${PI}" velocity="3" />
        <dynamics damping="1.0" friction="0.8" />
    </joint>

    <joint name="right_finger_joint" type="prismatic">
        <parent link="gripper" />
        <child link="right_finger" />
        <origin xyz="-0.005 -0.015 0" />
        <limit effort="100" lower="0" upper="${gripper_base_width/2}" velocity="0.1" />
        <mimic joint="Gripper" multiplier="-0.5" offset="${gripper_base_width/2}" />
        <dynamics damping="1.0" friction="0.16" />
    </joint>

    <joint name="left_finger_joint" type="prismatic">
        <parent link="gripper" />
        <child link="left_finger" />
        <origin xyz="0.005 -0.015 0" />
        <axis xyz="-1 0 0" />
        <limit effort="100" lower="0" upper="${gripper_base_width/2}" velocity="0.1" />
        <!-- Added an offset to fix issues in Rviz -->
        <mimic joint="right_finger_joint" offset="-0.0025" />
        <dynamics damping="1.0" friction="0.16" />
    </joint>

    <!-- Joint that accept the distance between the two fingers as parameter -->
    <joint name="Gripper" type="prismatic">
        <parent link="gripper" />
        <child link="gripper_mov" />
        <origin xyz="0.01 0  0" />
        <limit effort="10" lower="0" upper="${gripper_base_width}" velocity="0.1" />
        <axis xyz="-1 0 0" />
        <dynamics damping="5.0" />
        <!-- <dynamics friction="0.42" /> -->
    </joint>
    
</robot>
