<?xml version="1.0" ?>

<robot name="lynxmotion_al5d" xmlns:xacro="http://www.ros.org/wiki/xacro" xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    
    <xacro:include filename="$(find lynxmotion_al5d_description)/urdf/lynxmotion_al5d_properties.urdf.xacro" />

    <!-- Base link comprising the board behind the robot and the cylinder at its bottom -->
    <link name="world" />
    
    <link name="robot_support">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/support.dae" />
            </geometry>
        </visual>   
        <xacro:inertial_matrix_cylinder mass="0.4" height="0.04" radius="0.04" />
    </link>

    <link name="robot_base_cylinder">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/rotation_cylinder.dae" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 -0.021165 0" />
        </visual>
        <xacro:inertial_matrix_cylinder mass="0.05" height="0.004" radius="0.04" />
    </link>

    <link name="robot_base_top_box">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/top_box.dae" />
            </geometry>
            <origin xyz="0.007 -0.024 0" rpy="0 0 0" />
        </visual>
        <xacro:inertial_matrix_box mass="0.5" depth="0.03" height="0.04" width="0.06" />
    </link>
    <link name="shoulder">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/shoulder.dae" />
            </geometry>
            <origin rpy="${-PI/8} 0 0" xyz="0 -0.035 -0.06" />
        </visual>
        <xacro:inertial_matrix_box mass="0.5" depth="0.17" height="0.02" width="0.11" />
    </link>

    <link name="arm">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/arm.dae" />
            </geometry>
            <origin rpy="-0.895 0 0" xyz="0 ${-tube_length + 2*hs_755eb_depth/5} ${-shoulder_to_elbow - 0.02}" />
        </visual>
        <xacro:inertial_matrix_box mass="0.2" depth="0.03" height="0.07" width="0.05" />
    </link>

    <link name="wrist">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/wrist.dae" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0.165 -0.065" />
        </visual>
        <xacro:inertial_matrix_cylinder mass="0.05" height="0.01" radius="0.01" />
    </link>

    <link name="gripper">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/gripper.dae" />
            </geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0 0 0" />

        </visual>
        <xacro:inertial_matrix_box mass="0.2" depth="0.012" height="0.02" width="0.06" />
    </link>

    <link name="left_finger">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/finger_left.dae" />
            </geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0 0 0" />
        </visual>
        <xacro:inertial_matrix_box mass="0.2" depth="0.012" height="0.15" width="0.008" />
    </link>
            
    <link name="right_finger">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/finger_right.dae" />
            </geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0 0 0" />
        </visual>
        <xacro:inertial_matrix_box mass="0.2" depth="0.012" height="0.15" width="0.008" />
    </link>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.01 0.01 0.01" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 ${camera_support_depth}" />
            <material name="Transparent" />
        </visual>
    </link>

    <sensor name="robot_camera" update_rate="1">
        <parent link="camera_link" />
        <origin xyz="0.005 0.005 0.005" rpy="0 0 0" />
        <camera>
            <image width="640" height="480" hfov="${PI/2}" format="RGB8" near="${camera_support_depth}" far="${camera_support_depth}" />
        </camera>
    </sensor>

    <!-- Adding joints -->
    <joint name="world_to_robot" type="fixed">
        <parent link="world" />
        <child link="robot_support" />
    </joint>

    <joint name="camera_joint" type="fixed">
        <parent link="robot_support" />
        <child link="camera_link" />
        <origin xyz="0 -0.35 0" />
    </joint>

    <joint name="link1_rotz" type="revolute">
        <parent link="robot_support" />
        <child link="robot_base_cylinder" />
        <axis xyz="0 0 1" />
        <origin xyz="0 0.021 0" />
        <limit effort="10" velocity="1" lower="${-PI}" upper="${PI}" />
        <dynamics damping="50" friction="1" />
    </joint>

    <joint name="robot_base_fixed" type="fixed">
        <parent link="robot_base_cylinder" />
        <child link="robot_base_top_box" />
    </joint>
 
    <joint name="link1_rotx" type="revolute">
        <parent link="robot_base_top_box" />
        <child link="shoulder" />
        <axis xyz="1 0 0" />
        <origin xyz="0 -0.015 0.071" />
        <limit effort="10" velocity="1" lower="${-PI/2}" upper="${PI/2}" />
        <dynamics damping="50" friction="1" />
    </joint>

    <joint name="link2_rotx" type="revolute">
        <parent link="shoulder" />
        <child link="arm" />
        <axis xyz="1 0 0" />
        <origin xyz="0 0 ${shoulder_to_elbow}" />
        <limit effort="10" velocity="1" lower="${-PI/2}" upper="${PI/2}" />
        <dynamics damping="50" friction="1" />
    </joint>

    <joint name="link3_rotx" type="revolute">
        <parent link="arm" />
        <child link="wrist" />
        <axis xyz="1 0 0" />
        <origin xyz="0 ${-tube_length - hs_645_depth + 0.003} 0" />
        <limit effort="10" velocity="1" lower="${-PI/2}" upper="${PI/2}" />
        <dynamics damping="50" friction="1" />
    </joint>

    <joint name="link4_rotz" type="revolute">
        <parent link="wrist" />
        <child link="gripper" />
        <axis xyz="0 1 0" />
        <origin xyz="0 -0.055 0" rpy="0 0 0" />
        <limit effort="10" velocity="1" lower="${-PI}" upper="${PI}" />
        <dynamics damping="50" friction="1" />
    </joint>

    <joint name="finger_left_mov" type="prismatic">
        <parent link="gripper" />
        <child link="left_finger" />
        <limit effort="10" velocity="1" lower="0" upper="${-gripper_base_width/2}" />
    </joint>

    <joint name="finger_right_mov" type="prismatic">
        <parent link="gripper" />
        <child link="right_finger" />
        <limit effort="10" velocity="1" lower="0" upper="${gripper_base_width/2}" />
    </joint>

    
    <!-- Setting transmissions -->
    <transmission name="link1_rotx_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link1_rotx">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="link1_rotx_motor">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>
    <transmission name="link1_rotx_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link1_rotx">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="link1_rotx_motor">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <transmission name="link1_rotz_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link1_rotz">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="link1_rotz_motor">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <transmission name="link2_rotx_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link2_rotx">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="link2_rotx_motor">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <transmission name="link3_rotx_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link3_rotx">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="link3_rotx_motor">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <transmission name="link4_rotz_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link4_rotz">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="link4_rotz_motor">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <transmission name="fingers_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="finger_left_mov">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <joint name="finger_right_mov">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="fingers_motor">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>
</robot>
