<?xml version="1.0" ?>

<robot name="lynxmotion_al5d" xmlns:xacro="http://www.ros.org/wiki/xacro" xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    
    <xacro:include filename="$(find lynxmotion_al5d_description)/urdf/lynxmotion_al5d_properties.urdf.xacro" />

    <!-- Base link comprising the board behind the robot and the cylinder at its bottom -->
    
    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/base_link.dae" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>
        <xacro:inertial_matrix_cylinder height="${base_height}" radius="${base_radius}" mass="${base_mass}" />
    </link>
    
    <!-- Link representing the black box on top of the cylinder that rotates around the z axis in the link's frame of reference -->

    <link name="top_box">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/top_box.dae" />
            </geometry>
            <origin rpy="0 0 0" xyz="0.01 ${-top_box_height + base_radius} 0" />
        </visual>
        <collision>
            <geometry>
                <box size="${top_box_width} ${top_box_height} ${top_box_depth}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 ${-top_box_height + base_radius} ${top_box_depth/2}" />
        </collision>
        <xacro:inertial_matrix_box height="${top_box_height}" width="${top_box_width}" depth="${top_box_depth}" mass="${top_box_mass}" />
    </link>

    <!-- Link representing the second link of the robot (i.e the shoulder) -->

    <link name="shoulder">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/shoulder.dae" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${shoulder_width} ${shoulder_height} ${shoulder_to_elbow}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 ${shoulder_to_elbow/2}" />
        </collision>
        <xacro:inertial_matrix_box height="${shoulder_height}" width="${shoulder_width}" depth="${shoulder_to_elbow}" mass="${shoulder_mass}" />
    </link>

    <!-- Link representing the elbow of the robot which ends at the beginning of the wrist -->

    <link name="elbow">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/arm.dae" />
            </geometry>
            <origin xyz="0 -0.2 0" rpy="0 0 0" />
        </visual>
        <!--<visual name="before_arm">
            <geometry>
                <cylinder length="${tube_length}" radius="${tube_radius}" />
            </geometry>
            <material name="Silver" />
            <origin rpy="${PI/2} 0 0" xyz="0 ${-tube_length/2} 0" />
        </visual>
        <visual name="hs-755eb">
            <geometry>
                <box size="${hs_755eb_width} ${hs_755eb_height} ${hs_755eb_depth}" />
            </geometry>
            <material name="Black" />
            <origin rpy="0 0 0" xyz="0 0 0" />
        </visual> 
        <visual name="hs-645">
            <geometry>
                <box size="${hs_645_width} ${hs_645_height} ${hs_645_depth}" />
            </geometry>
            <material name="Black" />
            <origin rpy="${PI/2} 0 0" xyz="0 ${-tube_length} 0" />
        </visual> -->

        <collision>
            <geometry>
                <box size="${hs_755eb_width} ${hs_755eb_height} ${hs_755eb_depth}" />
            </geometry>
            <origin rpy="${PI/2} 0 0" xyz="0 ${-tube_length} 0" />
        </collision>
        <xacro:inertial_matrix_box height="${hs_755eb_height}" width="${hs_755eb_width}" depth="${hs_755eb_depth}" mass="${hs_755eb_mass}" />
    </link>

    <!-- Wrist of the robot -->

    <link name="wrist">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/wrist.dae" />
            </geometry>
        </visual>
        <!-- <visual>
            <geometry>
                <box size="${hs_225_width} ${hs_225_height} ${hs_225_depth}" />
            </geometry>
            <origin rpy="${PI/2} 0 0" xyz="0 0 0" />
            <material name="Black" />
        </visual>
        <visual name="wrist_cylinder">
            <geometry>
                <cylinder length="${wrist_cylinder_length}" radius="${wrist_cylinder_radius}" />
            </geometry>
            <origin rpy="${PI/2} 0 0" xyz="0 ${-(hs_225_depth/2 + wrist_cylinder_length/2)} 0" />
            <material name="Silver" />
        </visual> -->
        <collision>
            <geometry>
                <box size="${hs_225_width} ${hs_225_height} ${hs_225_depth}" />
            </geometry>
            <origin rpy="${PI/2} 0 0" xyz="0 0 0" />
        </collision>
        <xacro:inertial_matrix_box height="${hs_225_height}" width="${hs_225_width}" depth="${hs_225_depth}" mass="${hs_225_mass}" />
    </link>

    <!-- The solid structure below the gripper -->

    <link name="gripper_base">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/gripper_base.dae" />
            </geometry>
        </visual>
        <!-- <visual>
            <geometry>
                <box size="${gripper_base_width} ${gripper_base_height} ${gripper_base_depth}" />
            </geometry>
            <material name="Black" />
            <origin rpy="${PI/2} 0 0" xyz="0 0 0" />
        </visual>-->
        <collision>
            <geometry>
                <box size="${gripper_base_width} ${gripper_base_height} ${gripper_base_depth}" />
            </geometry>
            <origin rpy="${PI/2} 0 0" xyz="0 0 0" />
        </collision>
        <xacro:inertial_matrix_box height="${gripper_base_height}" width="${gripper_base_width}" depth="${gripper_base_depth}" mass="0.01" />
    </link>

    <!-- Left and right -->
    <link name="left_finger">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/finger_left.dae" />
            </geometry>
        </visual>
        <!-- <visual>
            <geometry>
                <box size="${finger_width} ${finger_height} ${finger_depth}" />
            </geometry>
            <origin rpy="${PI/2} 0 0" xyz="${gripper_base_width/2} ${-(wrist_cylinder_length + gripper_base_depth)} 0" />
            <material name="silver">
                <color rgba="0.8 0.8 0.8 1" />
            </material>
        </visual>--> 
        <collision>
            <geometry>
                <box size="${finger_width} ${finger_height} ${finger_depth}" />
            </geometry>
            <origin rpy="${PI/2} 0 0" xyz="${gripper_base_width/2} ${-(wrist_cylinder_length + gripper_base_depth)} 0" />
        </collision> 
        <xacro:inertial_matrix_box width="${finger_width}" height="${finger_height}" depth="${finger_depth}" mass="${finger_mass}" />
    </link>

    <link name="right_finger">
        <visual>
            <geometry>
                <mesh filename="package://lynxmotion_al5d_description/meshes/robot_parts/finger_right.dae" />
            </geometry>
        </visual>
        <!--<visual>
            <geometry>
                <box size="${finger_width} ${finger_height} ${finger_depth}" />
            </geometry>
            <origin rpy="${PI/2} 0 0" xyz="${-gripper_base_width/2} ${-(wrist_cylinder_length + gripper_base_depth)} 0" />
            <material name="silver">
                <color rgba="0.8 0.8 0.8 1" />
            </material>
        </visual> -->
        <collision>
            <geometry>
                <box size="${finger_width} ${finger_height} ${finger_depth}" />
            </geometry>
            <origin rpy="${PI/2} 0 0" xyz="${-gripper_base_width/2} ${-(wrist_cylinder_length + gripper_base_depth)} 0" />
        </collision> 
        <xacro:inertial_matrix_box width="${finger_width}" height="${finger_height}" depth="${finger_depth}" mass="${finger_mass}" />
    </link>

<xacro:property name="camera_support_depth" value="0.25" />
    <xacro:property name="camera_support_size" value="0.003" />
    <xacro:property name="camera_support_big_size" value="0.5" />
    <xacro:property name="camera_support_to_base" value="0.06" />

    <link name="camera_link">
        <visual name="stick">
            <geometry>
                <box size="${camera_support_size} ${camera_support_size} ${camera_support_depth}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 ${camera_support_to_base} ${camera_support_depth/2}" />
            <material name="BlueGrey" />
        </visual>
        <visual name="support">
            <geometry>
                <box size="${camera_support_big_size} ${camera_support_big_size + camera_support_to_base} ${camera_support_size}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 ${-camera_support_big_size/2} ${camera_support_depth - camera_support_size/2}" />
            <material name="BlueGrey" />
        </visual>
        <collision name="support">
            <geometry>
                <box size="${camera_support_big_size} ${camera_support_big_size + camera_support_to_base} ${camera_support_size}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 ${-camera_support_big_size/2} ${camera_support_depth - camera_support_size/2}" />
            <material name="BlueGrey" />
        </collision>
        <xacro:inertial_matrix_box mass="${camera_support_mass}" width="${camera_support_big_size}" height="${camera_support_big_size + camera_support_to_base}" depth="${camera_support_size}" />
    </link>

    <!-- Adding a camera sensor to the model -->
    <sensor name="robot_camera" update_rate="1">
        <parent link="camera_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <camera>
            <image width="640" height="480" hfov="${PI/2}" format="RGB8" near="${camera_support_depth}" far="${camera_support_depth}" />
        </camera>
    </sensor>

    <!-- Adding joints -->

    <joint name="camera_support_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
    </joint>

    <joint name="shoulder_elbow_roll" type="revolute">
        <parent link="base_link" />
        <child link="top_box" />
        <origin xyz="0 0 0" />
        <axis xyz="1 0 0" />
        <limit effort="10" velocity="1" lower="${-PI/2}" upper="${PI/2}" />
        <dynamics damping="50" friction="1" />
    </joint>

    <joint name="shoulder_elbow_yall" type="revolute">
        <parent link="top_box" />
        <child link="shoulder" />
        <origin xyz="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="10" velocity="1" lower="${-PI/2}" upper="${PI/2}" />
        <dynamics damping="50" friction="1" />
    </joint>

    <joint name="elbow_roll" type="revolute">
        <parent link="shoulder" />
        <child link="elbow" />
        <axis xyz="1 0 0" />
        <limit effort="10" velocity="1" lower="${-PI/2}" upper="${PI/2}" />
        <dynamics damping="50" friction="1" />
    </joint>

    <joint name="elbow_to_wrist_roll" type="revolute">
        <parent link="elbow" />
        <child link="wrist" />
        <origin xyz="0 ${-(tube_length+hs_645_height)} 0" />
        <axis xyz="1 0 0" />
        <limit effort="10" velocity="1" lower="${-PI/2}" upper="${PI/2}" />
        <dynamics damping="50" friction="1" />
    </joint>

    <joint name="gripper_base_pitch" type="revolute">
        <parent link="wrist" />
        <child link="gripper_base" />
        <origin xyz="0 ${-(hs_225_depth/2 + hs_645_height + wrist_cylinder_length)} 0" />
        <axis xyz="0 1 0" />
        <limit effort="10" velocity="1" lower="0" upper="${PI}" />
        <dynamics damping="50" friction="1" />
    </joint>

    <joint name="left_finger_mov" type="prismatic">
        <parent link="gripper_base" />
        <child link="left_finger" />
        <limit effort="10" velocity="1" lower="${-gripper_base_width/2}" upper="0" />
        <origin xyz="0 0 0" />
    </joint>

    <joint name="right_finger_mov" type="prismatic">
        <parent link="gripper_base" />
        <child link="right_finger" />
        <limit effort="10" velocity="1" lower="0" upper="${gripper_base_width/2}" />
        <origin xyz="0 0 0" />
    </joint>

    
    <!-- Setting transmissions -->

    <transmission name="link1_roll_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="shoulder_elbow_roll">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="link1_motor">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EfforJointInterface</hardwareInterface>
        </actuator>
    </transmission>
        
    <transmission name="link1_yall_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="shoulder_elbow_yall">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="link1_motor_2">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EfforJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <transmission name="link2_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="elbow_roll">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="link2_motor">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EfforJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <transmission name="link3_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="elbow_to_wrist_roll">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="link3_motor">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EfforJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <transmission name="link4_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="gripper_base_pitch">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="link4_motor">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EfforJointInterface</hardwareInterface>
        </actuator>
    </transmission>

    <transmission name="link1_roll_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_finger_mov">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <joint name="right_finger_mov">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="fingers_motors">
            <mechanicalReduction>10</mechanicalReduction>
            <hardwareInterface>EfforJointInterface</hardwareInterface>
        </actuator>
    </transmission>
</robot>
