lynxmotion_al5d:
    # Publish all joint states -----------------------------------
    angles:
        type: joint_state_controller/JointStateController
        publish_rate: 50  
  gazebo_ros_control:
    pid_gains:
      Joint1: {p: 100.0, i: 0.01, d: 10.0}
      Joint2: {p: 100.0, i: 0.01, d: 10.0}
      Joint3: {p: 100.0, i: 0.01, d: 10.0}
      Joint4: {p: 100.0, i: 0.01, d: 10.0}
      Joint5: {p: 100.0, i: 0.01, d: 10.0}
      Gripper: {p: 100.0, i: 0.01, d: 10.0}
      GripperBis: {p: 100.0, i: 0.01, d: 10.0}
