/gazebo_ros_control:
    pid_gains:
      Joint1: {p: 100.0, i: 0.01, d: 10.0}
      Joint2: {p: 100.0, i: 0.01, d: 10.0}
      Joint3: {p: 100.0, i: 0.01, d: 10.0}
      Joint4: {p: 100.0, i: 0.01, d: 10.0}
      Joint5: {p: 100.0, i: 0.01, d: 10.0}
      Gripper: {p: 20, i: 0.1, d: 0}
      GripperBis: {p: 20, i: 0.1, d: 0}

lynxmotion_al5d:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50  

    # Controller for all joints
    joints_positions:
        type: position_controllers/JointGroupPositionController
        joints:
            - Joint1
            - Joint2
            - Joint3
            - Joint4
            - Joint5
            - Gripper
            - GripperBis

# Added to remove the  physics while allowing control of the joints

/gazebo/set_physics_properties:
  time_step: 0.001
  max_update_rate: 1000.0
  gravity:
    x: 0.0
    y: 0.0
    z: 0.0
  ode_config:
    auto_disable_bodies: False
    sor_pgs_precon_iters: 0
    sor_pgs_iters: 0
    sor_pgs_w: 1.3
    sor_pgs_rms_error_tol: 0.0
    contact_surface_layer: 0.001
    contact_max_correcting_vel: 100.0
    cfm: 0.0
    erp: 0.2
    max_contacts: 20
